substitutions:
  _SERVICE: trm-eth-balance-api
  _REGION: us-central1

steps:
  # Create Artifact Registry repo if it doesn't exist
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud artifacts repositories describe ${_SERVICE} \
          --location=${_REGION} \
          --project=$PROJECT_ID 2>/dev/null || \
        gcloud artifacts repositories create ${_SERVICE} \
          --repository-format=docker \
          --location=${_REGION} \
          --project=$PROJECT_ID

  # Build image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE}/${_SERVICE}:latest"
      - "."

  # Push image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE}/${_SERVICE}:latest"

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run","deploy","${_SERVICE}",
        "--image","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_SERVICE}/${_SERVICE}:latest",
        "--region","${_REGION}",
        "--platform","managed",
        "--allow-unauthenticated",
        "--set-secrets","INFURA_API_KEY=infura-api-key:latest"
      ]


